/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        sv: {
          bg: "var(--sv-bg)",
          "bg-subtle": "var(--sv-bg-subtle)",
          "bg-surface": "var(--sv-bg-surface)",
          surface: "var(--sv-surface)",
          "surface-raised": "var(--sv-surface-raised)",
          "surface-hover": "var(--sv-surface-hover)",
          "surface-active": "var(--sv-surface-active)",
          border: "var(--sv-border)",
          "border-subtle": "var(--sv-border-subtle)",
          "border-focus": "var(--sv-border-focus)",
          "border-strong": "var(--sv-border-strong)",
          text: "var(--sv-text-primary)",
          "text-primary": "var(--sv-text-primary)",
          "text-secondary": "var(--sv-text-secondary)",
          "text-muted": "var(--sv-text-muted)",
          "text-disabled": "var(--sv-text-disabled)",
          "text-inverse": "var(--sv-text-inverse)",
          brand: {
            DEFAULT: "var(--sv-brand)",
            hover: "var(--sv-brand-hover)",
            subtle: "var(--sv-brand-subtle)",
            foreground: "var(--sv-brand-foreground)",
          },
          status: {
            success: "var(--sv-status-success)",
            warning: "var(--sv-status-warning)",
            error: "var(--sv-status-error)",
            info: "var(--sv-status-info)",
          },
          success: {
            DEFAULT: "var(--sv-status-success)",
            subtle: "var(--sv-success-subtle)",
            border: "var(--sv-success-border)",
            text: "var(--sv-success-text)",
          },
          warning: {
            DEFAULT: "var(--sv-status-warning)",
            subtle: "var(--sv-warning-subtle)",
            border: "var(--sv-warning-border)",
            text: "var(--sv-warning-text)",
          },
          error: {
            DEFAULT: "var(--sv-status-error)",
            subtle: "var(--sv-error-subtle)",
            border: "var(--sv-error-border)",
            text: "var(--sv-error-text)",
          },
          info: {
            DEFAULT: "var(--sv-status-info)",
            subtle: "var(--sv-info-subtle)",
            border: "var(--sv-info-border)",
            text: "var(--sv-info-text)",
          },
        },
        play: {
          bg: "var(--play-bg)",
          "bg-subtle": "var(--play-bg-subtle)",
          surface: "var(--play-surface)",
          "surface-alt": "var(--play-surface-alt)",
          "surface-subtle": "var(--play-surface-subtle)",
          "surface-hover": "var(--play-surface-hover)",
          "surface-raised": "var(--play-surface-raised)",
          border: "var(--play-border)",
          "border-subtle": "var(--play-border-subtle)",
          "border-strong": "var(--play-border-strong)",
          text: "var(--play-text)",
          "text-secondary": "var(--play-text-secondary)",
          "text-muted": "var(--play-text-muted)",
          "text-light": "var(--play-text-light)",
          "text-inverse": "var(--play-text-inverse)",
          brand: {
            DEFAULT: "var(--play-brand)",
            hover: "var(--play-brand-hover)",
            dark: "var(--play-brand-dark)",
            light: "var(--play-brand-light)",
          },
          accent: {
            DEFAULT: "var(--play-accent)",
            hover: "var(--play-accent-hover)",
            subtle: "var(--play-accent-subtle)",
          },
          status: {
            success: "var(--play-status-success)",
            warning: "var(--play-status-warning)",
            error: "var(--play-status-error)",
            info: "var(--play-status-info)",
          },
          success: {
            DEFAULT: "var(--play-status-success)",
            subtle: "var(--play-success-subtle)",
            border: "var(--play-success-border)",
            text: "var(--play-success-text)",
          },
          warning: {
            DEFAULT: "var(--play-status-warning)",
            subtle: "var(--play-warning-subtle)",
            border: "var(--play-warning-border)",
            text: "var(--play-warning-text)",
          },
          error: {
            DEFAULT: "var(--play-status-error)",
            subtle: "var(--play-error-subtle)",
            border: "var(--play-error-border)",
            text: "var(--play-error-text)",
          },
          info: {
            DEFAULT: "var(--play-status-info)",
            subtle: "var(--play-info-subtle)",
            border: "var(--play-info-border)",
            text: "var(--play-info-text)",
          },
        },
      },
      borderRadius: {
        "sv-xs": "var(--sv-radius-xs)",
        "sv-sm": "var(--sv-radius-sm)",
        "sv-md": "var(--sv-radius-md)",
        "sv-lg": "var(--sv-radius-lg)",
        "sv-xl": "var(--sv-radius-xl)",
        "sv-full": "var(--sv-radius-full)",
        "play-sm": "var(--play-radius-sm)",
        "play-md": "var(--play-radius-md)",
        "play-lg": "var(--play-radius-lg)",
        "play-xl": "var(--play-radius-xl)",
        "play-full": "var(--play-radius-full)",
        "play-pill": "var(--play-radius-pill)",
      },
      boxShadow: {
        "sv-sm": "var(--sv-shadow-sm)",
        "sv-md": "var(--sv-shadow-md)",
        "sv-lg": "var(--sv-shadow-lg)",
        "sv-xl": "var(--sv-shadow-xl)",
        "sv-glow": "var(--sv-shadow-glow)",
        "play-sm": "var(--play-shadow-sm)",
        "play-md": "var(--play-shadow-md)",
        "play-lg": "var(--play-shadow-lg)",
        "play-xl": "var(--play-shadow-xl)",
        "play-colored": "var(--play-shadow-colored)",
        "play-inner": "var(--play-shadow-inner)",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        play: ["var(--font-plus-jakarta)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      transitionTimingFunction: {
        "sv-default": "var(--sv-ease-default)",
        "sv-in": "var(--sv-ease-in)",
        "sv-out": "var(--sv-ease-out)",
        "sv-spring": "var(--sv-ease-spring)",
        "play-default": "var(--play-ease-default)",
        "play-spring": "var(--play-ease-spring)",
      },
      transitionDuration: {
        "sv-fast": "var(--sv-duration-fast)",
        "sv-normal": "var(--sv-duration-normal)",
        "sv-slow": "var(--sv-duration-slow)",
        "play-fast": "var(--play-duration-fast)",
        "play-normal": "var(--play-duration-normal)",
        "play-slow": "var(--play-duration-slow)",
      },
      animation: {
        marquee: 'marquee 25s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        }
      }
    },
  },
  plugins: [],
};

